settings:
  language: "en"  # Default language file (messages_en.yml)

  sensitivity:
    default:
      max_average_attack_interval: 150
      min_attack_count: 5
      max_std_deviation: 50.0
      tolerance_percentage: 0.80

    vip:
      max_average_attack_interval: 200
      min_attack_count: 10
      max_std_deviation: 60.0
      tolerance_percentage: 0.90

  actions:
    warn_player: true
    kick_player: false

  enabled: true

