# File: src/main/resources/plugin.yml
name: TriggerBotDetector
main: org.katsuki.triggerbotdetector.TriggerBotDetector
version: 1.0
description: A plugin to detect trigger bot hacks in Minecraft.
author: Katsuki
commands: []